### ISSUE TITLE
Reactor Control Computer crashes if the reactor is not linked, and it's viewed by a ghost.

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#759]
## Round ID:
Irrelevant

## Testmerges:
#758 

## Reproduction:
Click RCC that has no linked stormdrive as a ghost.

An interaction check is made for non-ghosts.

It does not occur for ghosts.
```
TypeError: Unable to get property 'constricted_plasma' of undefined or null reference
   at t.StormdriveConsole (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:6:86274)
   at Anonymous function (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:189973)
   at Anonymous function (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:189943)
   at Be (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:189921)
   at Anonymous function (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:189863)
   at Be (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:189805)
   at je (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:197069)
   at De (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:197308)
   at Anonymous function (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:120600)
   at Anonymous function (http://127.0.0.1:49035/tmp3468/tgui.bundle.js:1:120325)
```
`User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)`

**Comment by Corsaka** [comment]
Verified.
