### ISSUE TITLE
Error popup when fighter destroyed and deploying to escape pod. 

### ISSUE THREAD

**Issue by extramrdo** [BeeStation/NSV13#797]
Round 688 and a few prior.

**To Replicate**: Be Pilot with (Light) fighter. Click to get in fighter. Click fighter to pull up the main fighter popup with switches etc. Fly into space. Get shot. Become escape pod.
Observe: big blue popup, see below.
Click escape pod to bring up ship popup. Get blue error instead.
Use verb in Ship panel to bring up the main ship popup. Successfully get the main fighter popup that successfully labels you as Shipname - Escape Pod.

Issue reported from  Round ID: 688 (NSV 13 | Official | MRP | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1528

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Can't call method on undefined
   at e.exports (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:19490)
   at e.exports (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:12024)
   at keys (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:148564)
   at t.FighterControls (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:5:189534)
   at Anonymous function (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:189973)
   at Anonymous function (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:189943)
   at Be (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:189921)
   at Anonymous function (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:189863)
   at Be (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:189805)
   at je (http://127.0.0.1:50015/tmp16684/tgui.bundle.js:1:197069)

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0)

Nanotrasen (c) 2525-2559

**Comment by Jalleo** [comment]
Escape pods were removed from fighters
